theme: jekyll-theme-minimal
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: About
    url: setup/about

  - title: Setup Guide
    url: setup

  - title: Glazier Configurations
  - title: â””â”€New Actions
    url: setup/new_actions
  - title: â””â”€Config Layout
    url: setup/config_layout

  - title: YAML Files
  - title: â””â”€YAML Specs
    url: yaml
  - title: â””â”€Chooser UI
    url: yaml/chooser_ui
  - title: â””â”€YAML Tips
    url: yaml/tips

  - title: Python
  - title: â””â”€Installer Actions
    url: actions
  - title: â””â”€Policy Modules
    url: policies
  - title: â””â”€Error Handling
    url: error_codes
  - title: â””â”€Config Handlers
    url: setup/config_handlers

  - title: Mailing List ğŸ’Œ
    url: https://groups.google.com/forum/#!forum/glazier-discuss
  - title: File A Bug ğŸ›
    url: https://github.com/google/glazier/issues/new
