theme: jekyll-theme-minimal
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: â””â”€About
    url: setup/about
  - title: â””â”€Config Handlers
    url: setup/config_handlers
  - title: â””â”€Config Layout
    url: setup/config_layout
  - title: â””â”€New Actions
    url: setup/new_actions
  - title: â””â”€Error codes
    url: setup/error_codes
  - title: YAML
    url: yaml
  - title: â””â”€Chooser UI
    url: yaml/chooser_ui
  - title: â””â”€YAML Tips
    url: yaml/tips
  - title: Mailing List ğŸ’Œ
    url: https://groups.google.com/forum/#!forum/glazier-discuss
  - title: File A Bug ğŸ›
    url: https://github.com/google/glazier/issues/new
